# Generated by Django 3.0.8 on 2020-07-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('caption', models.TextField()),
                ('post', models.ImageField(upload_to='')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
