# Generated by Django 3.0.8 on 2020-07-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_button', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedcontent',
            name='post',
            field=models.ImageField(upload_to='.'),
        ),
    ]
