# Generated by Django 3.0.8 on 2020-07-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_button', '0002_auto_20200708_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedcontent',
            name='post',
            field=models.ImageField(upload_to=''),
        ),
    ]
